version: "3"

networks:
  web:
    driver: bridge

services:
  celery: #for starting celery
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "celery -A instafeed worker -B -l info"
    depends_on:
      - migrations
      - chrome

  migrations: # for migrations purposes after the server is up
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate"
    depends_on:
      - web-wsgi
      # - db

  web-wsgi:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0 -w 10  instafeed.wsgi:application --timeout 3000 --graceful-timeout 300
    expose:
      - 8000
    depends_on:
      - chrome
    volumes:
      - .:/code
    networks:
      - web
    environment:
      - DEBUG=FALSE

  nginx:
    build: ./nginx
    ports:
      - 8000:80
      - 80:80
      - 443:443
    depends_on:
      - web-wsgi
      - redis
    networks:
      - web
    volumes:
      - .:/code # for syncing with django source code
      - ./nginx:/etc/nginx/conf.d

  redis:
    image: redis:latest
    command: redis-server
    expose:
      - 6379

  # selenium-hub:
  #   image: selenium/hub:4.0.0-beta-1-prerelease-20210201
  #   container_name: selenium-hub
  #   ports:
  #     - "4442:4442"
  #     - "4443:4443"
  #     - "4444:4444"

  chrome:
    image: selenium/standalone-chrome:88.0-chromedriver-88.0
    # depends_on:
    #   - selenium-hub
    # environment:
    #   - SE_EVENT_BUS_HOST=selenium-hub
    #   - SE_EVENT_BUS_PUBLISH_PORT=4442
    #   - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    privileged: true
    shm_size: 2g
    networks:
      - web
    hostname: chrome
    ports:
      - "4449:4444"
    expose:
      - "4449"

  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   expose:
  #     - 5432

volumes:
  media:
  static:
