version: "3"

networks:
  web:
  celery-net:

services:
  celery: #for starting celery
    build: .
    command: bash -c "celery -A instafeed worker"
    networks:
      - celery-net
    depends_on:
      - chrome
      - migrations

  migrations: # for migrations purposes after the server is up
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations instagramscraper && python manage.py migrate"
    networks:
      - web
    depends_on:
      - web-wsgi
      - db
      - redis

  web-wsgi:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0 -w 10  instafeed.wsgi:application --timeout 3000 --graceful-timeout 300
    depends_on:
      - chrome
    expose:
      - 8000
    volumes:
      - .:/code
    networks:
      - web
      - celery-net
    environment:
      - DEBUG=FALSE

  nginx:
    build: ./nginx
    ports:
      - 8000:80
      - 443:80
      - 80:80
    depends_on:
      - web-wsgi
      - redis
    networks:
      - web
    volumes:
      - .:/code # for syncing with django source code
      - ./nginx:/etc/nginx/conf.d

  redis:
    image: redis:latest
    networks:
      - celery-net
    command: redis-server
    expose:
      - 6379

  chrome:
    image: selenium/standalone-chrome:88.0-chromedriver-88.0
    privileged: true
    shm_size: 2g
    networks:
      - web
    hostname: chrome
    ports:
      - "4449:4444"
    expose:
      - "4449"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    networks:
      - web
      - celery-net

volumes:
  media:
  static:
