version: 2.1

jobs:
  django-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: mkdir test-reports
      - run: sudo pip install selenium
      - run: sudo pip install requests
      - run: sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      - run: sudo apt-get -y update
      - run: sudo apt-get install -y google-chrome-stable
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app

  docker-dev-build:
    machine: true
    steps:
      - checkout
      - run:
          name: Building dev container
          command: |
            docker-compose -f docker-compose.dev.yml build
      - run:
          name: Running dev image
          command: |
            docker-compose -f docker-compose.dev.yml up -d
      - run:
          name: Stopping dev image
          command: |
            docker-compose -f docker-compose.dev.yml down

  python-linting:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: pip install flake8==3.8.4
      - run:
          command: flake8 ./ --max-line-length=120 --ignore=E402,F841,F401,E302,E305

workflows:
  ci:
    jobs:
      - python-linting
      - django-test:
          requires:
            - python-linting
