version: 2.1

jobs:
  django-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app

  docker-dev-build:
    machine: true
    steps:
      - checkout
      - run:
          name: Building dev container
          command: |
            docker-compose -f docker-compose.dev.yml build
      - run:
          name: Running dev image
          command: |
            docker-compose -f docker-compose.dev.yml up -d
      - run:
          name: Stopping dev image
          command: |
            docker-compose -f docker-compose.dev.yml down

  python-linting:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: pip install flake8==3.8.4
      - run:
          command: flake8 ./ --max-line-length=120 --ignore=E402,F841,F401,E302,E305

workflows:
  ci:
    jobs:
      - python-linting
      - django-test:
          requires:
            - python-linting
